{
 "title": "EduMetrics DevOps Overview",
 "tags": [
  "devops",
  "students-api"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Registered Students",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "student_count_total" }
   ]
  },
  {
   "title": "Average Students Attendance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "student_average_attendance" }
   ]
  },
  {
   "title": "Average Students Marks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "con" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "student_average_marks" }
   ]
  },
  {
   "title": "API Request Traffic Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (route, method)",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "95th Percentile API Latency (Response Time)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95 Latency"
    }
   ]
  },
  {
   "title": "Node.js Service CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m]) * 100",
     "legendFormat": "CPU Load"
    }
   ]
  },
  {
   "title": "Node.js Process RAM (RSS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "RSS Memory" }
   ]
  },
  {
   "title": "API Status Codes Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total) by (status_code)",
     "legendFormat": "Status {{status_code}}"
    }
   ]
  }
 ]
}